### ISSUE TITLE
Custom Placeholder Requirements for Channel Permissions

### ISSUE THREAD

**Issue by Silthus** [sVoxelDev/sChat#66]
```yaml
channels:
  test1:
    name: Test Channel
    settings:
      protected: true
      requirements:
        join:
         - type: placeholder
           check: "%vault_eco_balance% > 100000"
         - type: permission
           permission: 'schat.channel.test1.join'
```
